version: '3.7'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=app_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command: ["postgres", "-c", "log_statement=all"]

  redis:
    image: redis:latest

  app:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:postgres@posgres/app_db
    ports:
      - 8000:8000
    volumes:
      - ./:/app